[build]
  command = "yarn build" # the command you run to build this file
  publish = "build" # create-react-app builds to this folder, Netlify should serve all these files statically

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
